sudo: required

language: node_js

node_js:
  - "node"
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

script:
  - sudo pip install awscli
  - npm install
  - npm run build
  - aws s3 sync build/ s3://petreski-react-countries --delete
  - aws cloudfront create-invalidation --distribution-id=E2F18KNA2IIS8J --paths /