dependencies:
    override:
        - sudo pip install awscli
deployment:
  prod:
    branch: master
    commands:
      - npm run build
      - aws s3 sync build/ s3://petreski-react-countries
      - aws cloudfront create-invalidation --distribution-id=E2F18KNA2IIS8J --paths /